        // --- CONFIGURAÇÃO DE EVENTOS ---
        const eventos = [
            // Fevereiro/Março (Mês 2)
            {dia: 04, mes: 2, ano: 2026, nome: "SOAR: Ocultação",   link: "observacoes/soar.html?obs=Julio, Giuliano, Eros, Jonatã, Matheus&proj=Studying small Solar System bodies through stellar occultations&PI=Julio Camargo&links=2004GV9:https://lesia.obspm.fr/lucky-star/occ.php?p=150925&Nota=A ocultação ocupa apenas 2h da noite", classe: "event-soar" },
            
            {dia: 07, mes: 2, ano: 2026, nome: "1m60: Ocultação",   link: "observacoes/1m60.html?obs=Observação cancelada&proj=Studying small Solar System bodies through stellar occultations&PI=Julio Camargo&links=1996ST1:https://solarsystem.linea.org.br/prediction-event-detail/iB10E3k8u7od8knnMsid9w&plano=plano_da_noite/2026A/plano-da-noite__2025-10-28.txt&det=sparc4", classe: "event-1m60" },   
            {dia: 07, mes: 2, ano: 2026, nome: "Zeiss: Ocultação",   link: "observacoes/zeiss.html?obs=Giuliano, Jonatã, Tiago&proj=Studying small Solar System bodies through stellar occultations&PI=Julio Ignacio Bueno de Camargo&links=1996ST1:https://solarsystem.linea.org.br/prediction-event-detail/iB10E3k8u7od8knnMsid9w&det=ixon", classe: "event-zeiss" },  
            // Abril (Mês 3)
            {dia: 04,mes: 3,ano: 2026,nome: "ON: Ocultação", link:"observacoes/on.html?obs=Giuliano Margoti&proj=Observações de ocultações no Observatório Nacional&PI=Giuliano Margoti&links=2000CS8:https://solarsystem.linea.org.br/prediction-event-detail/uYhRLFF4Nl6PFLeRCX19tg&det=qhy", classe: "event-on"},
            {dia: 05,mes: 3,ano: 2026,nome: "ON: Ocultação", link:"observacoes/on.html?obs=Giuliano Margoti&proj=Observações de ocultações no Observatório Nacional&PI=Giuliano Margoti&links=Picasso:https://gaiamoons.imcce.fr/occ.php?p=91139&det=qhy", classe: "event-on"},
            {dia: 21,mes: 3,ano: 2026,nome: "ON: Ocultação", link:"observacoes/on.html?obs=Giuliano Margoti&proj=Observações de ocultações no Observatório Nacional&PI=Giuliano Margoti&links=Tauris:https://gaiamoons.imcce.fr/occ.php?p=111736&det=qhy", classe: "event-on"},
            {dia: 27,mes: 3,ano: 2026,nome: "ON: Ocultação", link:"observacoes/on.html?obs=Giuliano Margoti&proj=Observações de ocultações no Observatório Nacional&PI=Giuliano Margoti&links=Kodai:https://gaiamoons.imcce.fr/occ.php?p=96134&det=qhy", classe: "event-on"},

            {dia: 09,mes: 3,ano: 2026,nome: "1m60: Ocultação", link:"observacoes/1m60.html?obs=Observação cancelada&proj=Studying small Solar System bodies through stellar occultations&PI=Julio Ignacio Bueno de Camargo&links=Bernardinelli-Bernstein:https://lesia.obspm.fr/lucky-star/occ.php?p=155276&det=sparc4&plano=plano_da_noite/2026A/plano_da_noite__2026-04-09.txt", classe: "event-1m60"},
            {dia: 09,mes: 3,ano: 2026,nome: "IAG: Ocultação", link:"observacoes/iag.html?obs=Giuliano, Eros, Giovana&proj=Studying small Solar System bodies through stellar occultations&PI=Julio Ignacio Bueno de Camargo&links=Bernardinelli-Bernstein:https://lesia.obspm.fr/lucky-star/occ.php?p=155276&det=ikonl4&plano=plano_da_noite/2026A/plano_da_noite__2026-04-09.txt", classe: "event-iag"},
            {dia: 30,mes: 3,ano: 2026,nome: "1m60: Ocultação", link:"observacoes/1m60.html?obs=Jonatã, Giovana, Luiz, Matheus, Jacqueline&proj=Studying small Solar System bodies through stellar occultations&PI=Julio Ignacio Bueno de Camargo&links=Orcus:https://lesia.obspm.fr/lucky-star/occ.php?p=157033&det=sparc4&plano=plano_da_noite/2026A/plano_da_noite__2026-04-30.txt", classe: "event-1m60"},

            {dia: 10,mes: 3,ano: 2026,nome: "IAG: Rotação", link:"observacoes/iag.html?obs=Johannes, Helio, Matheus&proj=Rotation Photometry of the Trojan object (1143) Odysseus&PI=Johannes Antunes Nascimento Rodrigues&alvos=Odysseus&det=ikonl&plano=plano_da_noite/2026A/plano_da_noite__2026-04-10.txt", classe: "event-iag"},
            {dia: 11,mes: 3,ano: 2026,nome: "IAG: Rotação", link:"observacoes/iag.html?obs=Christian, Luana, Jacqueline&proj=Rotation Photometry of the Trojan object (1143) Odysseus&PI=Johannes Antunes Nascimento Rodrigues&alvos=Odysseus&det=ikonl&plano=plano_da_noite/2026A/plano_da_noite__2026-04-11.txt", classe: "event-iag"},
            {dia: 12,mes: 3,ano: 2026,nome: "IAG: Rotação", link:"observacoes/iag.html?obs=Giovana, Jonatã, Evelyn&proj=Rotation Photometry of the Trojan object (1143) Odysseus&PI=Johannes Antunes Nascimento Rodrigues&alvos=Odysseus&det=ikonl&plano=plano_da_noite/2026A/plano_da_noite__2026-04-12.txt", classe: "event-iag"},
            {dia: 13,mes: 3,ano: 2026,nome: "IAG: Rotação", link:"observacoes/iag.html?obs=Johannes, Viviane&proj=Rotation Photometry of the Trojan object (1143) Odysseus&PI=Johannes Antunes Nascimento Rodrigues&alvos=Odysseus&det=ikonl&plano=plano_da_noite/2026A/plano_da_noite__2026-04-13.txt", classe: "event-iag"},

            {dia: 22,mes: 3,ano: 2026,nome: "IAG: Rotação", link:"observacoes/iag.html?obs=Helio, Johannes, Gustavo&proj=Rotation light curves of the Jupiter's Trojan asteroid Diomedes, Nestor and Antilochus&PI=Helio Honório Dutra&alvos=Diomedes,Nestor,Antilochus&det=ikonl&plano=plano_da_noite/2026A/plano_da_noite__2026-04-22.txt", classe: "event-iag"},
            {dia: 23,mes: 3,ano: 2026,nome: "IAG: Rotação", link:"observacoes/iag.html?obs=Giovana, Viviane, Matheus&proj=Rotation light curves of the Jupiter's Trojan asteroid Diomedes, Nestor and Antilochus&PI=Helio Honório Dutra&alvos=Diomedes,Nestor,Antilochus&det=ikonl&plano=plano_da_noite/2026A/plano_da_noite__2026-04-23.txt", classe: "event-iag"},
            {dia: 24,mes: 3,ano: 2026,nome: "IAG: Rotação", link:"observacoes/iag.html?obs=Luiz, Jonatã, Gustavo&proj=Rotation light curves of the Jupiter's Trojan asteroid Diomedes, Nestor and Antilochus&PI=Helio Honório Dutra&alvos=Diomedes,Nestor,Antilochus&det=ikonl&plano=plano_da_noite/2026A/plano_da_noite__2026-04-24.txt", classe: "event-iag"},
            {dia: 25,mes: 3,ano: 2026,nome: "IAG: Rotação", link:"observacoes/iag.html?obs=Christian, Luana, Jacqueline&proj=Rotation light curves of the Jupiter's Trojan asteroid Diomedes, Nestor and Antilochus&PI=Helio Honório Dutra&alvos=Diomedes,Nestor,Antilochus&det=ikonl&plano=plano_da_noite/2026A/plano_da_noite__2026-04-25.txt", classe: "event-iag"},
            {dia: 26,mes: 3,ano: 2026,nome: "IAG: Rotação", link:"observacoes/iag.html?obs=Helio, Giovana, Evelyn&proj=Rotation light curves of the Jupiter's Trojan asteroid Diomedes, Nestor and Antilochus&PI=Helio Honório Dutra&alvos=Diomedes,Nestor,Antilochus&det=ikonl&plano=plano_da_noite/2026A/plano_da_noite__2026-04-26.txt", classe: "event-iag"},
            
            {dia: 30,mes: 3,ano: 2026,nome: "SOAR: Ocultação", link:"observacoes/soar.html?obs=Julio, Giuliano&proj=Studying small Solar System bodies through stellar occultations&PI=Julio Ignacio Bueno de Camargo&links=Orcus:https://lesia.obspm.fr/lucky-star/occ.php?p=157033", classe: "event-soar"},
            // Maio (Mês 4)
            {dia: 09,mes: 4,ano: 2026,nome: "ON: Ocultação", link:"observacoes/on.html?obs=Giuliano Margoti&proj=Observações de ocultações no Observatório Nacional&PI=Eros de Oliveira Gradovski&links=2004EW95:https://lesia.obspm.fr/lucky-star/occ.php?p=150797&det=qhy", classe: "event-on"},
            
            {dia: 05,mes: 4,ano: 2026,nome: "1m60: Ocultação", link:"observacoes/1m60.html?obs=Observadores a definir&proj=Studying small Solar System bodies through stellar occultations&PI=Julio Ignacio Bueno de Camargo&links=2014GU53:https://solarsystem.linea.org.br/prediction-event-detail/c04lknvkHGGgGZmNbX9hzg&det=sparc4", classe: "event-1m60"},
            {dia: 09,mes: 4,ano: 2026,nome: "1m60: Ocultação", link:"observacoes/1m60.html?obs=Observadores a definir&proj=Studying small Solar System bodies through stellar occultations&PI=Julio Ignacio Bueno de Camargo&links=2004EW95:https://lesia.obspm.fr/lucky-star/occ.php?p=150797&det=sparc4", classe: "event-1m60"},
            {dia: 14,mes: 4,ano: 2026,nome: "1m60: Ocultação", link:"observacoes/1m60.html?obs=Observadores a definir&proj=Studying small Solar System bodies through stellar occultations&PI=Julio Ignacio Bueno de Camargo&links=2007JH43:https://lesia.obspm.fr/lucky-star/occ.php?p=152275&det=sparc4", classe: "event-1m60"},

            {dia: 08,mes: 4,ano: 2026,nome: "IAG: Rotação", link:"observacoes/iag.html?obs=Observadores a definir&proj=Rotation Photometry of the Trojan object (1143) Odysseus&PI=Johannes Antunes Nascimento Rodrigues&alvos=Odysseus&det=ikonl", classe: "event-iag"},
            {dia: 09,mes: 4,ano: 2026,nome: "IAG: Rotação", link:"observacoes/iag.html?obs=Observadores a definir&proj=Rotation Photometry of the Trojan object (1143) Odysseus&PI=Johannes Antunes Nascimento Rodrigues&alvos=Odysseus&det=ikonl", classe: "event-iag"},
            {dia: 10,mes: 4,ano: 2026,nome: "IAG: Rotação", link:"observacoes/iag.html?obs=Observadores a definir&proj=Rotation Photometry of the Trojan object (1143) Odysseus&PI=Johannes Antunes Nascimento Rodrigues&alvos=Odysseus&det=ikonl", classe: "event-iag"},

            {dia: 20,mes: 4,ano: 2026,nome: "IAG: Rotação", link:"observacoes/iag.html?obs=Observadores a definir&proj=Rotation light curves of the Jupiter's Trojan asteroid Diomedes, Nestor and Antilochus&PI=Helio Honório Dutra&alvos=Diomedes,Nestor,Antilochus&det=ikonl", classe: "event-iag"},
            {dia: 21,mes: 4,ano: 2026,nome: "IAG: Rotação", link:"observacoes/iag.html?obs=Observadores a definir&proj=Rotation light curves of the Jupiter's Trojan asteroid Diomedes, Nestor and Antilochus&PI=Helio Honório Dutra&alvos=Diomedes,Nestor,Antilochus&det=ikonl", classe: "event-iag"},
            {dia: 22,mes: 4,ano: 2026,nome: "IAG: Rotação", link:"observacoes/iag.html?obs=Observadores a definir&proj=Rotation light curves of the Jupiter's Trojan asteroid Diomedes, Nestor and Antilochus&PI=Helio Honório Dutra&alvos=Diomedes,Nestor,Antilochus&det=ikonl", classe: "event-iag"},
            {dia: 23,mes: 4,ano: 2026,nome: "IAG: Rotação", link:"observacoes/iag.html?obs=Observadores a definir&proj=Rotation light curves of the Jupiter's Trojan asteroid Diomedes, Nestor and Antilochus&PI=Helio Honório Dutra&alvos=Diomedes,Nestor,Antilochus&det=ikonl", classe: "event-iag"},
            {dia: 24,mes: 4,ano: 2026,nome: "IAG: Rotação", link:"observacoes/iag.html?obs=Observadores a definir&proj=Rotation light curves of the Jupiter's Trojan asteroid Diomedes, Nestor and Antilochus&PI=Helio Honório Dutra&alvos=Diomedes,Nestor,Antilochus&det=ikonl", classe: "event-iag"},

            {dia: 10,mes: 4,ano: 2026,nome: "SOAR: Rotação", link:"observacoes/soar.html?obs=Observadores a definir&proj=Rotational Characterization of Trans-Neptunian Object 90568 Goibniu (2004 GV9)&PI=Giuliano Margoti&alvos=90568 Goibniu (2004 GV9)&det=goodman", classe: "event-soar"},
            // Junho (Mês 5)
            {dia: 08,mes: 5,ano: 2026,nome: "SOAR: Ocultação", link:"observacoes/soar.html?obs=Observadores a definir&proj=Studying small Solar System bodies through stellar occultations&PI=Julio Ignacio Bueno de Camargo&links=Ixion:https://lesia.obspm.fr/lucky-star/occ.php?p=156507", classe: "event-soar"},
            
            {dia: 14,mes: 5,ano: 2026,nome: "SOAR: Rotação", link:"observacoes/soar.html?obs=Observadores a definir&proj=Obtaining rotation light curves of Neptune and Uranus Trojans to determine their 3D shapes&PI=Eros de Oliveira Gradovski&alvos=2013KY18,2011QF99,2010EN65&det=goodman", classe: "event-soar"},
            {dia: 15,mes: 5,ano: 2026,nome: "SOAR: Rotação", link:"observacoes/soar.html?obs=Observadores a definir&proj=Obtaining rotation light curves of Neptune and Uranus Trojans to determine their 3D shapes&PI=Eros de Oliveira Gradovski&alvos=2013KY18,2011QF99,2010EN65&det=goodman", classe: "event-soar"},

            {dia: 28,mes: 5,ano: 2026,nome: "1m60: Ocultação", link:"observacoes/1m60.html?obs=Observadores a definir&proj=Studying small Solar System bodies through stellar occultations&PI=Julio Ignacio Bueno de Camargo&links=Ixion:https://lesia.obspm.fr/lucky-star/occ.php?p=156514&det=sparc4", classe: "event-1m60"},
            // Julho (Mês 6)
            {dia: 13,mes: 6,ano: 2026,nome: "SOAR: Ocultação", link:"observacoes/soar.html?obs=Observadores a definir&proj=Studying small Solar System bodies through stellar occultations&PI=Julio Ignacio Bueno de Camargo&links=Eurípilos:https://lesia.obspm.fr/lucky-star/occ.php?p=156305", classe: "event-soar"},
            {dia: 24,mes: 6,ano: 2026,nome: "SOAR: Ocultação", link:"observacoes/soar.html?obs=Observadores a definir&proj=Studying small Solar System bodies through stellar occultations&PI=Julio Ignacio Bueno de Camargo&links=Ixion (principal):https://lesia.obspm.fr/lucky-star/occ.php?p=156525,Ixion:https://lesia.obspm.fr/lucky-star/occ.php?p=156524", classe: "event-soar"},
            
            {dia: 24,mes: 6,ano: 2026,nome: "1m60: Ocultação", link:"observacoes/1m60.html?obs=Observadores a definir&proj=Studying small Solar System bodies through stellar occultations&PI=Julio Ignacio Bueno de Camargo&links=Ixion (principal):https://lesia.obspm.fr/lucky-star/occ.php?p=156525,Ixion:https://lesia.obspm.fr/lucky-star/occ.php?p=156524&det=sparc4", classe: "event-1m60"},
            // Agosto (Mês 7)
            {dia: 07,mes: 7,ano: 2026,nome: "1m60: Ocultação", link:"observacoes/1m60.html?obs=Observadores a definir&proj=Studying small Solar System bodies through stellar occultations&PI=Julio Ignacio Bueno de Camargo&links=2002KX14:https://lesia.obspm.fr/lucky-star/occ.php?p=150107&det=sparc4", classe: "event-1m60"},

        ];
